CREATE DATABASE doingsdone_146479
 DEFAULT CHARACTER SET utf8
 DEFAULT COLLATE utf8_general_ci;

USE doingsdone_146479;

CREATE TABLE users (
user_id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
registration_date DATETIME NOT NULL,
email VARCHAR(128) UNIQUE NOT NULL,
name VARCHAR(128) NOT NULL,
password VARCHAR(128) NOT NULL
);

CREATE TABLE projects (
project_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(128) NOT NULL,
user_id INT UNSIGNED NOT NULL,
FOREIGN KEY (user_id) REFERENCES users (user_id)
);

CREATE TABLE tasks (
task_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
create_date DATETIME NOT NULL,
execution_date DATETIME NOT NULL,
status TINYINT UNSIGNED DEFAULT 0 NOT NULL,
name VARCHAR(255) NOT NULL,
file VARCHAR(255),
period DATETIME,
user_id INT UNSIGNED NOT NULL,
project_id INT UNSIGNED NOT NULL,
FOREIGN KEY (user_id) REFERENCES users (user_id),
FOREIGN KEY (project_id) REFERENCES projects (project_id)
);



